### Sub Charts Specific Values ###
backend:
  enabled: false
payment:
  enabled: true
im-central-server:
  enabled: true
im-security-server:
  enabled: true
ui:
  enabled: false
open-imis-backend:
  enabled: true
open-imis-db:
  enabled: true
digital-registries-emulator:
  enabled: false