name: "frontend"
replicaCount: 1
labels: 
  app: "frontend"
template:
  labels: 
    app: "frontend"
containers:
  name: frontend
  image: 463471358064.dkr.ecr.eu-central-1.amazonaws.com/app/usct/frontend:latest
  imagePullPolicy: "Always"
profiles: "container"
service:
  name: "frontend"
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: false
  # Annotations for the ingress
  annotations:
    # Default annotations if ingress is nginx ingress
    # Allow HTTP false
    kubernetes.io/ingress.allow-http: "false"
    # Ingress class as NGINX
    kubernetes.io/ingress.class: nginx
    # Enable CORS
    nginx.ingress.kubernetes.io/enable-cors: "true"
    # Proxy buffer size
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
  # Hosts
  hosts:
    - host: usct-frontend.example.com
      paths:
        - path: /
          pathType: Prefix
  # TLS
  tls:
    - hosts:
        - usct-frontend.example.com
      secretName: tls-secret